export enum HeadsUpDetailEnum {
  NON_FREE_SEAT = 'NO_ADVANCE_SEAT_AVAILABLE',
  EXTRA_SEAT = 'EXTRA_SEAT_PERSON',
  UMNR_SEAT = 'UNACCOMPANIED_MINOR',
  UMNR_EXTRA_SEAT = 'UMNR_EXTRA_SEAT',
  UMNR_MUSICAL_INSTRUMENT = 'UMNR_MUSICAL_INSTRUMENT',
  EXTRA_SEATS_INSTRUMENT = 'EXTRA_SEATS_INSTRUMENT',
  MUSICAL_INSTRUMENT = 'MUSICAL_INSTRUMENT',
  MINT_CABIN_UNAVAILABLE = 'MINT_CABIN_UNAVAILABLE',
}
